# docker-compose.yml
services:
  frontend:
    container_name: healthcare-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules   # Prevents local node_modules from overwriting container's
    environment:
      - NODE_ENV=development
    command: npm run dev
